### ISSUE TITLE
Fails to build with libjxl v0.9: use of undeclared identifier 'JXL_DEC_EXTENSIONS'

### ISSUE THREAD

**Issue by lazka** [cgohlke/imagecodecs#90]
The last libjxl release removed some deprecated things and changed API/ABI in some places: https://github.com/libjxl/libjxl/releases/tag/v0.9.0

The build currently fails like this (there might be more issues):

```c
imagecodecs/_jpegxl.c:20938:51: error: use of undeclared identifier 'JXL_DEC_EXTENSIONS'
 20938 |     __pyx_t_3 = __Pyx_PyInt_From_JxlDecoderStatus(JXL_DEC_EXTENSIONS); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 91, __py...
       |                                                   ^
1 warning and 1 error generated.
error: command 'C:\\msys64\\clang64\\bin/clang.exe' failed with exit code 1
```

Here is how other projects deal with the API differences, as an example: https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/970/diffs

**Comment by cgohlke** [comment]
That's already fixed in the development version. The next release will require libjxl 0.9.x.

**Comment by cgohlke** [comment]
Should be fixed in v2024.1.1.
