### ISSUE TITLE
Installation on linux

### ISSUE THREAD

**Issue by haseeb33** [cgohlke/imagecodecs#16]
I want to install the latest version on Linux. I have tried both ways.

1. ```pip install imagecodecs```
It installs **2020.5.30** version, no matter what I do

2. python setup.py install
It tries to install the latest version(2021.3.31) but it throws an error.

Terminal output::
> python setup.py install
> running install
> running bdist_egg
> running egg_info
> writing imagecodecs.egg-info/PKG-INFO
> writing dependency_links to imagecodecs.egg-info/dependency_links.txt
> writing entry points to imagecodecs.egg-info/entry_points.txt
> writing requirements to imagecodecs.egg-info/requires.txt
> writing top-level names to imagecodecs.egg-info/top_level.txt
> reading manifest file 'imagecodecs.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no files found matching '3rdparty/*'
> warning: no files found matching 'tests/*.zfp'
> warning: no files found matching 'tests/*.tif'
> warning: no previously-included files found matching 'tests/tiff/gray.movie.u1.tif'
> warning: no previously-included files found matching 'tests/libaec/121B2TestData/ExtendedParameters/*.*'
> warning: no previously-included files found matching 'tests/33792x79872.jpg'
> warning: no previously-included files found matching 'tests/jpegxr.czi'
> warning: no previously-included files matching '__pycache__' found under directory '*'
> warning: no previously-included files matching '*.py[co]' found under directory '*'
> warning: no previously-included files matching '*-' found under directory '*'
> warning: no previously-included files matching '*.html' found under directory '*'
> warning: no previously-included files matching '*Copy*.*' found under directory '*'
> writing manifest file 'imagecodecs.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> skipping 'imagecodecs/_aec.c' Cython extension (up-to-date)
> skipping 'imagecodecs/_bitshuffle.c' Cython extension (up-to-date)
> skipping 'imagecodecs/_blosc.c' Cython extension (up-to-date)
> building 'imagecodecs._blosc' extension
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iimagecodecs -I/usr/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -c imagecodecs/_blosc.c -o build/temp.linux-x86_64-3.6/imagecodecs/_blosc.o
> In file included from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
>                  from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
>                  from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
>                  from imagecodecs/_blosc.c:593:
> /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
>  #warning "Using deprecated NumPy API, disable it with " \
>   ^
> imagecodecs/_blosc.c:597:19: fatal error: blosc.h: No such file or directory
> compilation terminated.
> **error: command 'x86_64-linux-gnu-gcc' failed with exit status 1**

**Comment by cgohlke** [comment]
v2020.5.30 is the last version that works with Python 3.6.

To build newer versions from source for Python >=3.7, try the instructions at https://github.com/cgohlke/imagecodecs/blob/2ef2a2ebb4e5b8ea7289c6e2fc6ea289e870af48/imagecodecs/imagecodecs.py#L140-L171
